### ISSUE TITLE
transform-origin property is not properly minimized

### ISSUE THREAD

**Issue by caristu** [barryvan/CSSMin#21]
The CSSMin class is not handling properly the "transform-origin" property. 
This property can have up three arguments (one per axis)[1]. The default value is "50% 50% 0".

If not all the parameters are defined it does not mean that the remaining ones have the same value, i.e., the 'simplified' version generated after minimize it is not equivalent.

Therefore, the same fix applied for the "background-size"[1] should be applied for the "transform-origin" property.

[1] https://www.w3schools.com/cssref/css3_pr_transform-origin.asp
[2] https://github.com/barryvan/CSSMin/commit/24d4ed987a1b52e46e544369038346b084fad595

**Comment by barryvan** [comment]
Fixed by #22 -- thanks @caristu!
